### PR TITLE
Update slack info & times on tutorials post

### PR DESCRIPTION
**Pull request by hauten**
Added specific blocks of time for each tutorial. Removed Slack link since we'll be adding people after they register.

### CODE REVIEW

**Comment by hauten** [comment]
@vsoch if you have time to expedite, that would be great; but ok if not! the twitterverse is asking for these details :)

**Review by vsoch — COMMENTED** [review]
One tiny suggestion - if we remove spaces from the times it renders nicely (first row)

image

vs not (the following row). E.g., so the text I used is just `8:00a.m.–11:30a.m.` I think if we could tweak that detail it would be perfecto!

**Comment by hauten** [comment]
ok spaces are tweaked!

**Comment by vsoch** [comment]
haha it just made the column smaller! But I still think this is easier to read since the second time isn't truncated. Let's ship it!

image

**Review by vsoch — APPROVED** [review]

**Comment by hauten** [comment]
thank you very much

**Comment by vsoch** [comment]
thank you! :t-rex: :avocado:

**Pull request merged**
