### PR TITLE
Initial commit of AWS tutorial page

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by vsoch** [comment]
@davidbeckingsale this isn't the right place for this - I think we need a separate tutorials place.

**Comment by davidbeckingsale** [comment]
This is not where the tutorials will go, just the page advertising them.

**Comment by vsoch** [comment]
Yeah I don't agree with that design either - if we have some form of announcements, it should be more akin to a blog with a post that has a category or tag for tutorial (we could call it a blog, news, or just general posts/announcements), and not a hard coded "tutorial-2022" page. Does that make sense?

**Comment by davidbeckingsale** [comment]
Blog post would be fine by me - this was just what I could put together fastest.

Can you take this content and put it in the blog-style format you are imagining?

**Comment by vsoch** [comment]
@davidbeckingsale yep on it! We will need some major changes to the template, I'll do my best!

**Comment by vsoch** [comment]
This needs a formal design with posts that have tags or categories - we can't just do it quickly because of the deadline and not do a good job. I'll work on it locally and see what I can come up with.

**Pull request closed without merging**
